name: Enhancement
description: Suggest an enhancement to an existing feature for mo_ctl
title: "[Enhancement]: "
labels: [type/enhancement]
assignees:
  - aronchanisme
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the enhancement?
      description: Please check if an issue already exists for your enhancement.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Enhancement Description
      description: Describe your idea on what you want, and why you want it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Enhancement Implementation
      description: Describe how you would like a implement the enhancement
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other more information you want to tell us.
    validations:
      required: false