name: Feature Request
description: Suggest an idea of new feature for mo_ctl
title: "[Feature Request]: "
labels: [type/feature]
assignees:
  - aronchanisme
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the feature request?
      description: Please check if an issue already exists for your feature request.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe your idea on what you want, and why you want it.
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Implementation
      description: Describe how you would like a implement the feature
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other more information you want to tell us.
      render: Markdown
    validations:
      required: false